### ISSUE TITLE
Multiple serviceActivations

### ISSUE THREAD

**Issue by dinoo** [seesharper/LightInject.Wcf#1]
I have an example project with two services/endpoints located in the same service hosting environment: FooService and BarService. The service implementations are located in FooService.Library namespace and the interfaces are defined in FooService.Contracts namespace. One of the two services has a repository that must be injected.

My original solution was to create my own Factory, ServiceHost, InstanceProvider, ServiceBehavior that would manage the ServiceContainer and pass it down to the InstanceProvider to perform the instance creation of my service.

Instead I wanted to use LightInject.Wcf, by just changing the factory to the LightInject factory in my web.config. However, I am getting the following error.

> Only interfaces with [ServiceContract] attribute are supported with LightInjectServiceHostFactory.

Do you have any tips for my scenario?
### Contracts

``` csharp
using System.ServiceModel;

namespace FooService.Contracts
{
    [ServiceContract]
    public interface IFooService
    {
        [OperationContract]
        string ServiceAction();
    }

    [ServiceContract]
    public interface IBarService
    {
        [OperationContract]
        string ServiceAction();
    }
}
```
### Services / Repository / CompositionRoot

``` csharp
using FooService.Contracts;
using System.ServiceModel;
using System;

namespace FooService.Library
{
    [ServiceBehavior(InstanceContextMode = InstanceContextMode.PerCall, ConcurrencyMode = ConcurrencyMode.Multiple)]
    public class FooService : IFooService
    {
        public string ServiceAction()
        {
            return Guid.NewGuid().ToString();
        }
    }

    [ServiceBehavior(InstanceContextMode = InstanceContextMode.PerCall, ConcurrencyMode = ConcurrencyMode.Multiple)]
    public class BarService : IBarService
    {
        private IBarRepository repository;

        public BarService(IBarRepository repository)
        {
            this.repository = repository;
        }

        public string ServiceAction()
        {
            return repository.GetItem();
        }
    }

    public class BarRepository : IBarRepository
    {
        public string GetItem()
        {
            return "ITEM";
        }
    }

    public class CompositionRoot : ICompositionRoot
    {
        public void Compose(IServiceRegistry serviceRegistry)
        {
            serviceRegistry.Register<IBarRepository, BarRepository>();
            serviceRegistry.Register<IFooService, FooService>();
            serviceRegistry.Register<IBarService, BarService>();
        }
    }
}
```
### web.config

``` xml
  <system.serviceModel>
    <serviceHostingEnvironment multipleSiteBindingsEnabled="true">
      <serviceActivations>
        <add factory="LightInject.Wcf.LightInjectServiceHostFactory, LightInject.Wcf"
          relativeAddress="./Foo.svc"
          service="FooService.Library.FooService" />
        <add factory="LightInject.Wcf.LightInjectServiceHostFactory, LightInject.Wcf"
          relativeAddress="./Bar.svc"
          service="FooService.Library.BarService" />
      </serviceActivations>
    </serviceHostingEnvironment>
    <behaviors>
      <serviceBehaviors>
        <behavior>
          <serviceMetadata httpGetEnabled="true"/>
        </behavior>
      </serviceBehaviors>
    </behaviors>
  </system.serviceModel>
```

**Comment by seesharper** [comment]
Is this a standalone app or IIS? Could you put a "working" example up on GitHub and I will have a look at it

**Comment by dinoo** [comment]
The service is hosted IIS.

I put the sample on [GitHub](https://github.com/dinoo/LightInject.Wcf.Sample)

**Comment by dinoo** [comment]
I merged your pull request and did a test, but I got an error. I have enabled "includeExceptionDetailInFaults" and got the following exception back.

``` xml
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <s:Fault>
         <faultcode xmlns:a="http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher">a:InternalServiceFault</faultcode>
         <faultstring xml:lang="en-US">Unable to resolve type: FooService.Contracts.IFooService, service name:</faultstring>
         <detail>
            <ExceptionDetail xmlns="http://schemas.datacontract.org/2004/07/System.ServiceModel" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
               <HelpLink i:nil="true"/>
               <InnerException i:nil="true"/>
               <Message>Unable to resolve type: FooService.Contracts.IFooService, service name:</Message>
               <StackTrace><![CDATA[at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:line 3752
   at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:line 3723
   at LightInject.ServiceContainer.GetInstance(Type serviceType) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:line 2391
   at LightInject.Wcf.LightInjectServiceHostFactory.<>c__DisplayClass7.<CreateProxyDefinition>b__4() in c:\Users\bri\AppData\Local\Temp\ranut2g2\LightInject.Wcf\LightInject.Wcf.cs:line 280
   at LightInject.Interception.ProxyBuilder.<>c__DisplayClass51_0`1.<CreateGenericTargetFactory>b__0() in C:\projects\lightinject-interception\build\tmp\Net46\Binary\LightInject.Interception\LightInject.Interception.cs:line 1420
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at IFooServiceProxy.LightInject.Interception.IProxy.get_Target()
   at LightInject.Interception.TargetInvocationInfo.Proceed() in C:\projects\lightinject-interception\build\tmp\Net46\Binary\LightInject.Interception\LightInject.Interception.cs:line 672
   at LightInject.Wcf.ServiceInterceptor.Invoke(IInvocationInfo invocationInfo) in c:\Users\bri\AppData\Local\Temp\ranut2g2\LightInject.Wcf\LightInject.Wcf.cs:line 347
   at IFooServiceProxy.ServiceAction()
   at SyncInvokeServiceAction(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)]]></StackTrace>
               <Type>System.InvalidOperationException</Type>
            </ExceptionDetail>
         </detail>
      </s:Fault>
   </s:Body>
</s:Envelope>
```

**Comment by dinoo** [comment]
Thanks for your help in getting me on my way. I would say this issue is resolved.
